CREATE OR REPLACE TABLE RAW.RESTAURANTS(
RESTAURANT_ID INT,
RESTAURANT_NAME STRING,
CITY STRING,
CUISINE_TYPE STRING,
RATING NUMBER(2,1));

CREATE OR REPLACE TABLE RAW.CUSTOMERS(
CUSTOMER_ID INT,
CUSTOMER_NAME STRING,
CITY STRING,
SIGNUP_DATE DATE);

CREATE OR REPLACE TABLE RAW.FOOD_ORDERS(
ORDER_ID INT,
CUSTOMER_ID INT,
RESTAURANT_ID INT,
ORDER_DATE DATE,
ORDER_AMOUNT NUMBER(10,2),
DELIVERY_FEE NUMBER(10,2),
DISCOUNT_AMOUNT NUMBER(10,2),
ORDER_STATUS STRING,
PAYMENT_METHOD STRING,
DELIVERY_MINUTES INT);

-- Add 15-20 inserts including duplicate and invalid records.
