CREATE OR REPLACE VIEW STAGING.INVALID_ORDERS_VW AS
SELECT *,
CASE
WHEN ORDER_AMOUNT<=0 THEN 'INVALID AMOUNT'
WHEN ORDER_STATUS NOT IN ('PLACED','PREPARING','OUT_FOR_DELIVERY','DELIVERED','CANCELLED') THEN 'INVALID STATUS'
WHEN ORDER_STATUS='DELIVERED' AND DELIVERY_MINUTES IS NULL THEN 'MISSING DELIVERY TIME'
END AS VALIDATION_MESSAGE
FROM RAW.FOOD_ORDERS;

CREATE OR REPLACE VIEW STAGING.CLEAN_ORDERS_VW AS
WITH DEDUP AS(
SELECT *,
ROW_NUMBER() OVER(PARTITION BY ORDER_ID ORDER BY ORDER_DATE DESC) RN
FROM RAW.FOOD_ORDERS)
SELECT *,
ORDER_AMOUNT+DELIVERY_FEE-DISCOUNT_AMOUNT AS NET_ORDER_VALUE
FROM DEDUP
WHERE RN=1;
