CREATE OR REPLACE VIEW ANALYTICS.RESTAURANT_PERFORMANCE_VW AS
SELECT R.RESTAURANT_NAME,
COUNT(*) TOTAL_ORDERS,
SUM(C.ORDER_AMOUNT+C.DELIVERY_FEE-C.DISCOUNT_AMOUNT) TOTAL_REVENUE
FROM STAGING.CLEAN_ORDERS_VW C
JOIN RAW.RESTAURANTS R
ON C.RESTAURANT_ID=R.RESTAURANT_ID
GROUP BY 1;

-- Top 3 customers
SELECT CUSTOMER_ID,
SUM(NET_ORDER_VALUE) TOTAL_SPEND
FROM STAGING.CLEAN_ORDERS_VW
GROUP BY 1
ORDER BY 2 DESC
LIMIT 3;
