-- ===================================
-- DATA VALIDATION QUERIES
-- ===================================

-- Validation Rule 1: ORDER_AMOUNT must be greater than zero
CREATE OR REPLACE VIEW VALIDATION_ORDER_AMOUNT AS
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    RESTAURANT_ID,
    ORDER_AMOUNT,
    'VALIDATION FAILED: ORDER_AMOUNT must be > 0' AS VALIDATION_MESSAGE,
    CURRENT_TIMESTAMP() AS VALIDATION_TIME
FROM 
    FOOD_ORDERS
WHERE 
    ORDER_AMOUNT <= 0
ORDER BY 
    ORDER_ID;

-- Validation Rule 2: ORDER_STATUS must be one of PLACED, PREPARING, OUT_FOR_DELIVERY, DELIVERED, or CANCELLED
CREATE OR REPLACE VIEW VALIDATION_ORDER_STATUS AS
-- Validation Rule 2: ORDER_STATUS must be one of
-- Pending, Confirmed, Preparing, Ready, In Transit, Delivered, or Cancelled
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    RESTAURANT_ID,
    ORDER_STATUS,
    'VALIDATION FAILED: Invalid ORDER_STATUS value' AS VALIDATION_MESSAGE,
    CURRENT_TIMESTAMP() AS VALIDATION_TIME
FROM 
    RAW.FOOD_ORDERS
WHERE 
    ORDER_STATUS NOT IN ('Pending', 'Confirmed', 'Preparing', 'Ready', 'In Transit', 'Delivered', 'Cancelled')
ORDER BY 
    ORDER_ID;

-- Validation Rule 3: RESTAURANT_ID must exist in RAW.RESTAURANTS
CREATE OR REPLACE VIEW VALIDATION_RESTAURANT_ID AS
SELECT 
    fo.ORDER_ID,
    fo.CUSTOMER_ID,
    fo.RESTAURANT_ID,
    'VALIDATION FAILED: RESTAURANT_ID does not exist in RESTAURANTS table' AS VALIDATION_MESSAGE,
    CURRENT_TIMESTAMP() AS VALIDATION_TIME
FROM 
    FOOD_ORDERS fo
LEFT JOIN 
    RESTAURANTS r ON fo.RESTAURANT_ID = r.RESTAURANT_ID
WHERE 
    r.RESTAURANT_ID IS NULL
ORDER BY 
    fo.ORDER_ID;

-- Validation Rule 4: A DELIVERED order must contain DELIVERY_MINUTES (not NULL)
CREATE OR REPLACE VIEW VALIDATION_DELIVERY_MINUTES AS
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    RESTAURANT_ID,
    ORDER_STATUS,
    DELIVERY_MINUTES,
    'VALIDATION FAILED: DELIVERED order missing DELIVERY_MINUTES' AS VALIDATION_MESSAGE,
    CURRENT_TIMESTAMP() AS VALIDATION_TIME
FROM 
    FOOD_ORDERS
WHERE 
    ORDER_STATUS = 'Delivered' AND DELIVERY_MINUTES IS NULL
ORDER BY 
    ORDER_ID;

-- Validation Rule 5: Only one row per ORDER_ID may appear in the clean staging view
CREATE OR REPLACE VIEW VALIDATION_DUPLICATE_ORDER_ID AS
SELECT 
    ORDER_ID,
    COUNT(*) AS DUPLICATE_COUNT,
    'VALIDATION FAILED: Duplicate ORDER_ID detected' AS VALIDATION_MESSAGE,
    CURRENT_TIMESTAMP() AS VALIDATION_TIME
FROM 
    FOOD_ORDERS
GROUP BY 
    ORDER_ID
HAVING 
    COUNT(*) > 1
ORDER BY 
    ORDER_ID;

-- ===================================
-- CONSOLIDATED VALIDATION REPORT
-- ===================================

-- Master validation view combining all rules
CREATE OR REPLACE VIEW MASTER_VALIDATION_REPORT AS
SELECT 'Rule 1' AS RULE_ID, 'ORDER_AMOUNT > 0' AS RULE_DESCRIPTION, COUNT(*) AS VIOLATIONS_COUNT
FROM VALIDATION_ORDER_AMOUNT
UNION ALL
SELECT 'Rule 2', 'Valid ORDER_STATUS', COUNT(*)
FROM VALIDATION_ORDER_STATUS
UNION ALL
SELECT 'Rule 3', 'RESTAURANT_ID exists', COUNT(*)
FROM VALIDATION_RESTAURANT_ID
UNION ALL
SELECT 'Rule 4', 'DELIVERED order has DELIVERY_MINUTES', COUNT(*)
FROM VALIDATION_DELIVERY_MINUTES
UNION ALL
SELECT 'Rule 5', 'No duplicate ORDER_ID', COUNT(*)
FROM VALIDATION_DUPLICATE_ORDER_ID;

-- Detailed validation summary
CREATE OR REPLACE VIEW VALIDATION_SUMMARY AS
SELECT 
    CASE 
        WHEN (SELECT COUNT(*) FROM VALIDATION_ORDER_AMOUNT) > 0 THEN 'FAILED'
        WHEN (SELECT COUNT(*) FROM VALIDATION_ORDER_STATUS) > 0 THEN 'FAILED'
        WHEN (SELECT COUNT(*) FROM VALIDATION_RESTAURANT_ID) > 0 THEN 'FAILED'
        WHEN (SELECT COUNT(*) FROM VALIDATION_DELIVERY_MINUTES) > 0 THEN 'FAILED'
        WHEN (SELECT COUNT(*) FROM VALIDATION_DUPLICATE_ORDER_ID) > 0 THEN 'FAILED'
        ELSE 'PASSED'
    END AS OVERALL_VALIDATION_STATUS,
    (SELECT COUNT(*) FROM VALIDATION_ORDER_AMOUNT) AS RULE1_VIOLATIONS,
    (SELECT COUNT(*) FROM VALIDATION_ORDER_STATUS) AS RULE2_VIOLATIONS,
    (SELECT COUNT(*) FROM VALIDATION_RESTAURANT_ID) AS RULE3_VIOLATIONS,
    (SELECT COUNT(*) FROM VALIDATION_DELIVERY_MINUTES) AS RULE4_VIOLATIONS,
    (SELECT COUNT(*) FROM VALIDATION_DUPLICATE_ORDER_ID) AS RULE5_VIOLATIONS,
    ((SELECT COUNT(*) FROM VALIDATION_ORDER_AMOUNT) +
     (SELECT COUNT(*) FROM VALIDATION_ORDER_STATUS) +
     (SELECT COUNT(*) FROM VALIDATION_RESTAURANT_ID) +
     (SELECT COUNT(*) FROM VALIDATION_DELIVERY_MINUTES) +
     (SELECT COUNT(*) FROM VALIDATION_DUPLICATE_ORDER_ID)) AS TOTAL_VIOLATIONS,
    CURRENT_TIMESTAMP() AS VALIDATION_TIMESTAMP;
